# Generated by Django 3.2.12 on 2022-04-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lasname', models.CharField(max_length=20)),
                ('email_client', models.EmailField(default='Some String', max_length=254)),
                ('phone', models.IntegerField()),
                ('messege', models.CharField(max_length=20)),
            ],
        ),
    ]
