# Generated by Django 3.2.12 on 2022-04-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='email',
        ),
    ]
