# Generated by Django 3.2.12 on 2022-04-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_estudiante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='email',
            field=models.EmailField(default='string', max_length=254),
            preserve_default=False,
        ),
    ]
